# (Numerical Python) NumPy is a Python library.NumPy is used for working with arrays.In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

## If you have Python and PIP already installed on a system, then installation of NumPy is very easy.Install it using this command:   C:\Users\Your Name>pip install numpy

In [56]:
##Import NumPy. (NumPy package can be referred to as np instead of numpy.)

In [57]:
import numpy as np

In [58]:
#Checking NumPy Version

In [59]:
print(np.__version__)

1.20.1


In [60]:
#Create a NumPy ndarray Object. We can create a NumPy ndarray object by using the array() function.

In [61]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [62]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [64]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

In [65]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [66]:
#Check Number of Dimensions?
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [67]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [68]:
#Create an array with 4 dimensions and verify that it has 4 dimensions:

In [69]:
arr = np.array(([1, 2, 3, 4],[4, 5, 6, 7]), ndmin=4)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[1 2 3 4]
   [4 5 6 7]]]]
number of dimensions : 4


In [70]:
#Access Array Elements. Array indexing is the same as accessing an array element.You can access an array element by referring to its index number.

In [71]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [72]:
#Get third and fourth elements from the following array and add them.

In [73]:
print(arr[2] + arr[3])

7


In [74]:
#Access 2-D Arrays. To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

In [75]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Second element on 1st dimensions : ', arr[0, 1])

Second element on 1st dimensions :  2


In [76]:
#Access 3-D Arrays. To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [77]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [78]:
#Negative Indexing. Print the last element from the 2nd dimensions:

In [79]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10],[10,15,8,16,25]])
print('Last element from 2nd dimensions: ', arr[1, -1])

Last element from 2nd dimensions:  10


# NumPy Array Slicing
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [80]:
# Slice elements from index 1 to index 5 from the following array:

In [81]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [82]:
# Slice elements from index 4 to the end of the array:

In [83]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [84]:
# Slice elements from the beginning to index 4 

In [85]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [86]:
# Negative Slicing
# Slice from the index 3 from the end to index 1 from the end:

In [87]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


# STEP
Use the step value to determine the step of the slicing:
Return every other element from index 1 to index 5:

In [88]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [89]:
#Return every other element from the entire array:

In [90]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [91]:
#Slicing 2-D Arrays
#From the second element, slice elements from index 1 to index 4(not included)

In [92]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [93]:
#From both elements, return index 3:

In [94]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 3])

[4 9]


In [95]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

In [96]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer |
b - boolean |
u - unsigned integer |
f - float |
c - complex float |
m - timedelta |
M - datetime |
O - object |
S - string |
U - unicode string |
V - fixed chunk of memory for other type ( void ) 

# Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:
Get the data type of an array object:

In [97]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [98]:
#Get the data type of an array containing strings:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


# Creating Arrays With a Defined Data Type
Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

# Create an array with data type string:

arr = np.array([1, 2, 3, 4], dtype='U')
print(arr)
print(arr.dtype)


In [99]:
#For i, u, f, S and U we can define size as well.

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# A non integer string like 'a' can not be converted to integer (will raise an error):

In [100]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
#Change data type from float to integer by using 'i' as parameter value:

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

In [ ]:
#Change data type from float to integer by using int as parameter value:

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

In [ ]:
#Change data type from integer to boolean:

arr = np.array([-1, 0, -100])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

#COPY: 
Make a copy, change the original array, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

# VIEW:
Make a view, change the original array, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

# The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

# NumPy Array Shape
## Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

### The example above returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.

# #Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

# NumPy Array Reshaping

Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

# Reshape From 1-D to 3-D

Convert the following 1-D array with 12 elements into a 3-D array.
The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

### Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

# Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

# NumPy Array Iterating
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

In [ ]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

In [ ]:
#Iterate on the elements of the following 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

In [ ]:
#Iterate on each scalar element of the 2-D array:

for x in arr:
  for y in x:
    print(y)

In [ ]:
#Iterate on the elements of the following 3-D array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

In [ ]:
##Iterate on each scalar element of the 2-D array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples. 

In [101]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


## Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [104]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)
print(arr.dtype)

b'1'
b'2'
b'3'
int32


# Iterating With Different Step Size
We can use filtering and followed by iteration.
Iterate through every scalar element of the 2D array skipping 1 element:

In [105]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


# Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [106]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
#Enumerate on following 2D array's elements:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

# Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.
In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [107]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [108]:
#Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [109]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

In [110]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [111]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


# Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [112]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [115]:
#Split the array in 3 parts:

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [116]:
#Access the splitted arrays:

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.
Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [117]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [118]:
#Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


# The example above returns three 2-D arrays.

In addition, you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the row (axis=1).
Split the 2-D array into three 2-D arrays along rows.

In [119]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [121]:
#An alternate solution is using hsplit() opposite of hstack()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

#Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPy Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.
To search an array, use the where() method.

In [122]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [123]:
#The example above will return a tuple: (array([3, 5, 6],)
#Which means that the value 4 is present at index 3, 5, and 6.

In [124]:
#Find the indexes where the values are even:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [125]:
#Find the indexes where the values are odd:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


# Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

In [129]:
#Find the indexes where the value 7 should be inserted:

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [127]:
#Find the indexes where the value 7 should be inserted, starting from the right:

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [128]:
#Find the indexes where the values 2, 4, and 6 should be inserted:

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


#### The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.

# NumPy Sorting Arrays

Sorting means putting elements in an ordered sequence.
Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [131]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [132]:
#Sort the array alphabetically:

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [133]:
#Sort a boolean array:

arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [134]:
#Sort a 2-D array:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# NumPy Filter Array

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [135]:
#Create an array from the elements on index 0 and 2:

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


#### The example above will return [41, 43], why?

Because the new filter contains only the values where the filter array had the value True, in this case, index 0 and 2.

# Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.


In [136]:
#Create a filter array that will return only values higher than 42:

arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [137]:
#Create a filter array that will return only even elements from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


## Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [138]:
#Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [139]:
#Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
